from __future__ import annotations

from pathlib import Path

from .architect import build_architecture
from .context_loader import load_context
from .executor import Executor
from .fixer import Fixer
from .memory_manager import MemoryManager
from .planner import create_plan
from .project_state import summarize_project
from .requirements_extractor import extract_requirements
from .sandbox_guard import SandboxGuard
from .structure_planner import plan_file_structure
from .tester import Tester
from .version_detector import detect_version


MAX_FIX_ATTEMPTS = 5


def run(workdir: Path) -> int:

    version = detect_version(workdir)
    guard = SandboxGuard(version.current_dir)

    guard.resolve("memory").mkdir(parents=True, exist_ok=True)
    memory = MemoryManager(guard)

    ctx = load_context(version.current_dir, version.previous_dir)
    memory.append_devlog("Loaded context from current and previous version.")

    requirements = extract_requirements(ctx.task_text, guard)
    memory.write_text("requirements.md", "\n".join(f"- {item}" for item in requirements))
    memory.append_devlog("Extracted requirements with LLM.")

    architecture = build_architecture(requirements, guard)
    memory.write_text("architecture.md", architecture)
    memory.append_devlog("Prepared architecture with LLM.")

    plan = create_plan(architecture, guard)
    memory.write_json("plan.json", plan)
    memory.append_devlog("Saved plan.json generated by LLM.")

    structure = plan_file_structure(memory, guard)
    memory.append_devlog(
        f"File structure planned: src={len(structure['src'])}, tests={len(structure['tests'])}"
    )

    executor = Executor(guard)

    generated: list[Path] = []

    # structure phase
    generated.extend(executor.generate_structure_from_plan())

    # implementation phase
    generated.extend(executor.implement_modules())

    # dependency validation
    generated.extend(executor.validate_dependencies())

    # source validation before tests
    source_issues = executor.validate_source_code()

    # fix source validation issues before tests
    if source_issues:
        source_report = "\n".join(
            f"file: {issue['file']}\nerror_type: {issue['error_type']}\nmessage: {issue['message']}"
            for issue in source_issues
        )
        memory.append_devlog("Source validation found issues; invoking fixer before test generation.")
        pretest_fixer = Fixer(version.current_dir, guard)
        fix_note = pretest_fixer.apply(source_report, context="source_validation")
        memory.append_devlog(f"Pre-test fix: {fix_note}")

    # extract API for test generation
    executor.extract_api()

    # generate tests ONCE
    generated.extend(executor.generate_tests_from_structure())

    memory.append_devlog(
        "Generated files: "
        + ", ".join(str(path.relative_to(version.current_dir)) for path in generated)
    )

    tester = Tester(version.current_dir)
    fixer = Fixer(version.current_dir, guard)

    tests_passed = False

    for attempt in range(1, MAX_FIX_ATTEMPTS + 1):

        memory.append_devlog(f"Validation attempt {attempt}")

        result = tester.run()

        guard.resolve("tests/test_results.md").write_text(
            f"# Validation attempt {attempt}\n\n```\n{result.output}\n```\n",
            encoding="utf-8",
        )

        if result.success:
            tests_passed = True
            break

        fix_note = fixer.apply(result.output)
        memory.append_devlog(f"Fix attempt {attempt}: {fix_note}")

    if not tests_passed:

        memory.write_text(
            "blocked.md",
            "# Blocked\n\nValidation failed after maximum attempts.\n",
        )

        memory.append_devlog("Stopped due to max validation attempts.")
        return 1

    state = summarize_project(version.current_dir, guard)
    memory.write_text("project_state.md", state)
    memory.append_devlog("Updated project_state.md")

    memory.write_text(
        "context.md",
        "Project finalized: all tests passed, no active bugs.",
    )

    memory.write_text(
        "bugs.md",
        "# Bugs\n\nNo active bugs.\n",
    )

    memory.write_text("blocked.md", "")

    memory.append_devlog("Pipeline completed successfully.")

    return 0